#include "GameCodeGen.hpp"
#include <fstream>
#include <filesystem>
#include <cstdio>

namespace fs = std::filesystem;

bool GameCodeGen::GenerateGame1(const std::string& projectPath,
                                 const std::string& projectName,
                                 int screenW, int screenH,
                                 glm::vec4 bgColor)
{
    fs::path game1Path = fs::path(projectPath) / "Game1.cs";

    std::ofstream f(game1Path.string(), std::ios::trunc);
    if (!f.is_open()) return false;

    // Convert 0-1 float color to 0-255 ints for C# Color(int,int,int)
    int bgR = static_cast<int>(bgColor.r * 255.f + 0.5f);
    int bgG = static_cast<int>(bgColor.g * 255.f + 0.5f);
    int bgB = static_cast<int>(bgColor.b * 255.f + 0.5f);

    f <<
R"(// AUTO-GENERATED by MonoPoly IDE — safe to add partial classes, do not rename Game1.
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text.Json;

namespace )" << projectName << R"(
{
    // -------------------------------------------------------------------------
    // Base class for entity scripts. Extend this in your own .cs files.
    // Game1 discovers all subclasses automatically via reflection.
    // -------------------------------------------------------------------------
    public abstract class EntityScript
    {
        /// Called once after the scene is loaded.
        public virtual void Start(SceneEntity entity) { }

        /// Called every frame. Modify entity.X / entity.Y / entity.Rotation, etc.
        public abstract void Update(SceneEntity entity, GameTime gameTime);
    }

    // -------------------------------------------------------------------------
    // Runtime representation of a scene entity (mirrors .mpscene JSON).
    // -------------------------------------------------------------------------
    public sealed class SceneEntity
    {
        public string Name        { get; set; } = "Entity";
        public float  X           { get; set; }
        public float  Y           { get; set; }
        public float  ScaleX      { get; set; } = 100f;
        public float  ScaleY      { get; set; } = 100f;
        public float  Rotation    { get; set; }
        public string TextureName { get; set; } = "";
        public float  R           { get; set; } = 1f;
        public float  G           { get; set; } = 1f;
        public float  B           { get; set; } = 1f;
        public float  A           { get; set; } = 1f;

        // Keyboard movement (set by "keyboard_movement" component in editor)
        public bool  HasKeyboard { get; set; }
        public float MoveSpeed   { get; set; } = 200f;
        public bool  LockX       { get; set; }
        public bool  LockY       { get; set; }
        public bool  UseWASD     { get; set; } = true;
        public bool  UseArrows   { get; set; } = true;

        // Script binding (set by "script" component in editor)
        public string ScriptClass { get; set; } = "";
    }

    // -------------------------------------------------------------------------
    // Main game class (auto-generated skeleton — add logic in partial classes).
    // -------------------------------------------------------------------------
    public partial class Game1 : Game
    {
        private GraphicsDeviceManager _graphics;
        private SpriteBatch           _spriteBatch;
        private readonly List<(SceneEntity entity, Texture2D tex)> _sprites = new();
        private readonly Dictionary<SceneEntity, EntityScript>     _scripts = new();
        private Texture2D _whitePixel;

        public Game1()
        {
            _graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
            IsMouseVisible        = true;
            _graphics.PreferredBackBufferWidth  = )" << screenW << R"(;
            _graphics.PreferredBackBufferHeight = )" << screenH << R"(;
        }

        protected override void Initialize() => base.Initialize();

        protected override void LoadContent()
        {
            _spriteBatch = new SpriteBatch(GraphicsDevice);
            _whitePixel  = new Texture2D(GraphicsDevice, 1, 1);
            _whitePixel.SetData(new[] { Color.White });
            LoadScene("Scene.mpscene");
            LoadScripts();
        }

        // -- Scene loading ----------------------------------------------------
        private void LoadScene(string path)
        {
            if (!File.Exists(path)) return;
            using var doc = JsonDocument.Parse(File.ReadAllText(path));
            if (doc.RootElement.TryGetProperty("entities", out var arr))
                ParseEntities(arr);
        }

        private void ParseEntities(JsonElement arr)
        {
            foreach (var je in arr.EnumerateArray())
            {
                var e = new SceneEntity();

                if (je.TryGetProperty("tag", out var t))
                    e.Name = t.GetString() ?? "Entity";

                if (je.TryGetProperty("transform", out var tf))
                {
                    if (tf.TryGetProperty("position", out var p))
                    { e.X = p.GetProperty("x").GetSingle(); e.Y = p.GetProperty("y").GetSingle(); }
                    if (tf.TryGetProperty("scale", out var s))
                    { e.ScaleX = s.GetProperty("x").GetSingle(); e.ScaleY = s.GetProperty("y").GetSingle(); }
                    if (tf.TryGetProperty("rotation", out var rot)) e.Rotation = rot.GetSingle();
                }

                Texture2D tex = _whitePixel;
                bool hasSpriteRenderer = je.TryGetProperty("sprite_renderer", out var sr);
                if (hasSpriteRenderer)
                {
                    if (sr.TryGetProperty("texture_path", out var tp) &&
                        tp.GetString() is { Length: > 0 } name)
                        try { tex = Content.Load<Texture2D>(name); } catch { }

                    if (sr.TryGetProperty("color", out var col))
                    {
                        e.R = col.GetProperty("r").GetSingle();
                        e.G = col.GetProperty("g").GetSingle();
                        e.B = col.GetProperty("b").GetSingle();
                        e.A = col.GetProperty("a").GetSingle();
                    }
                }

                // Keyboard movement component
                if (je.TryGetProperty("keyboard_movement", out var km))
                {
                    e.HasKeyboard = true;
                    if (km.TryGetProperty("speed",      out var sp)) e.MoveSpeed  = sp.GetSingle();
                    if (km.TryGetProperty("lock_x",     out var lx)) e.LockX      = lx.GetBoolean();
                    if (km.TryGetProperty("lock_y",     out var ly)) e.LockY      = ly.GetBoolean();
                    if (km.TryGetProperty("use_wasd",   out var uw)) e.UseWASD    = uw.GetBoolean();
                    if (km.TryGetProperty("use_arrows", out var ua)) e.UseArrows  = ua.GetBoolean();
                }

                // Script component
                if (je.TryGetProperty("script", out var sc) &&
                    sc.TryGetProperty("class", out var cn))
                    e.ScriptClass = cn.GetString() ?? "";

                // Only tracked if it has something to render
                if (hasSpriteRenderer)
                    _sprites.Add((e, tex));

                // Recurse children
                if (je.TryGetProperty("children", out var ch)) ParseEntities(ch);
            }
        }

        // -- Script discovery via reflection ----------------------------------
        private void LoadScripts()
        {
            var asm = Assembly.GetExecutingAssembly();
            foreach (var (e, _) in _sprites)
            {
                if (string.IsNullOrEmpty(e.ScriptClass)) continue;
                var type = asm.GetType(e.ScriptClass);
                if (type == null || !typeof(EntityScript).IsAssignableFrom(type)) continue;
                try
                {
                    var script = (EntityScript)Activator.CreateInstance(type)!;
                    script.Start(e);
                    _scripts[e] = script;
                }
                catch { /* class exists but can't be instantiated — skip */ }
            }
        }

        // -- Update -----------------------------------------------------------
        protected override void Update(GameTime gameTime)
        {
            if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed ||
                Keyboard.GetState().IsKeyDown(Keys.Escape))
                Exit();

            float dt = (float)gameTime.ElapsedGameTime.TotalSeconds;
            var   kb = Keyboard.GetState();

            foreach (var (e, _) in _sprites)
            {
                // Built-in keyboard movement
                if (e.HasKeyboard)
                {
                    float dx = 0f, dy = 0f;
                    if (e.UseWASD)
                    {
                        if (kb.IsKeyDown(Keys.A)) dx -= e.MoveSpeed * dt;
                        if (kb.IsKeyDown(Keys.D)) dx += e.MoveSpeed * dt;
                        if (kb.IsKeyDown(Keys.W)) dy += e.MoveSpeed * dt;
                        if (kb.IsKeyDown(Keys.S)) dy -= e.MoveSpeed * dt;
                    }
                    if (e.UseArrows)
                    {
                        if (kb.IsKeyDown(Keys.Left))  dx -= e.MoveSpeed * dt;
                        if (kb.IsKeyDown(Keys.Right)) dx += e.MoveSpeed * dt;
                        if (kb.IsKeyDown(Keys.Up))    dy += e.MoveSpeed * dt;
                        if (kb.IsKeyDown(Keys.Down))  dy -= e.MoveSpeed * dt;
                    }
                    if (!e.LockX) e.X += dx;
                    if (!e.LockY) e.Y += dy;
                }

                // Entity script
                if (_scripts.TryGetValue(e, out var script))
                    script.Update(e, gameTime);
            }

            base.Update(gameTime);
        }

        // -- Draw -------------------------------------------------------------
        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(new Color()" << bgR << ", " << bgG << ", " << bgB << R"());
            _spriteBatch.Begin(samplerState: SamplerState.PointClamp);

            int hw = GraphicsDevice.Viewport.Width  / 2;
            int hh = GraphicsDevice.Viewport.Height / 2;

            foreach (var (e, tex) in _sprites)
            {
                var color    = new Color(e.R, e.G, e.B, e.A);
                var position = new Vector2(hw + e.X, hh - e.Y);  // editor Y-up -> screen Y-down
                var scale    = new Vector2(e.ScaleX / tex.Width, e.ScaleY / tex.Height);
                var origin   = new Vector2(tex.Width * 0.5f, tex.Height * 0.5f);
                _spriteBatch.Draw(tex, position, null, color, e.Rotation, origin, scale,
                                  SpriteEffects.None, 0f);
            }

            _spriteBatch.End();
            base.Draw(gameTime);
        }
    }
}
)";

    return true;
}
